# this is a config file for Poxy - a Doxygen + m.css front-end written in Python.
# https://github.com/marzer/poxy

name                = 'OpenIW'
author              = 'OpenIW'
description         = 'IW Engine for Call of Duty® games.'
cpp                 = 23
github              = 'OpenIW/OpenIW'
license             = [ 'GPLv3', 'https://github.com/OpenIW/OpenIW/blob/master/LICENSE' ]
favicon             = 'favicon.png'
navbar              = [ 'namespaces', 'files' ]
theme               = 'dark'

[warnings]
enabled             = true
undocumented        = true
treat_as_errors     = false

[sources]
recursive_paths     = [ '../src' ]
patterns            = [ '*.h' , '*.cpp' ]
